name: Python Pipeline

on: [push]

env:
  FILE_NAME: hello-py

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run python code
      run: python hello.py

        
  Build:
    needs: [Test]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: hello
        path: .
